### ISSUE TITLE
Installation via devtools fails because of `humdrumR` symlink

### ISSUE THREAD

**Issue by chfin** [Computational-Cognitive-Musicology-Lab/humdrumR#1]
The symlink `humdrumR` points to an invalid location, which makes `cp` fail when installing the package with 
```
devtools::install_github("Computational-Cognitive-Musicology-Lab/humdrumR")
```

**Comment by natsguitar** [comment]
I've fixed that symlink bug, and added some installation instructions. If you could try installing again, I'd love to hear if its working.

**Comment by chfin** [comment]
Two things:
1. I added `dependencies = TRUE` to `install_github`, otherwise it complained about `knitr` being missing.
2. I still get the following error:
    ```
    Error : (konvertiert von Warnung) /tmp/RtmpMtpYCZ/R.INSTALL13ca96214d34a/humdrumR/man/Humtable.Rd:63: unknown macro '\item'
    ERROR: installing Rd objects failed for package ‘humdrumR’
    ```

**Comment by natsguitar** [comment]
Sorry I never responded to this. Please let me know if you are continuing to have problems.
